version: '3'

services:
  resurrect.us.web:
    image: resurrect.us.web
    ports:
       - 5001:80
    build:
      context: ./Resurrect.Us.Web
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "12Admin345"
      ACCEPT_EULA: "Y"
